---
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: ensure service is disabled if requested
  become: yes
  service:
    name: nginx
    enabled: no
  when: not nginx_service_enabled
  notify:
    - stop nginx
