---
- name: ensure php5-cgi is installed
  sudo: yes
  apt: pkg=php5-cgi
  tags:
    - php5

- name: ensure additional extensions are installed
  sudo: yes
  apt: pkg={{ item }}
  with_items: php_extensions
  tags:
    - php5
