---
- name: Update apt cache
  become: yes
  apt:
    update_cache: yes
  tags:
    - common

- name: Ensure task dependencies are installed
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
  tags:
    - common
